### ISSUE TITLE
Object reference error when synchronizing a clean install of the Dancing Goat Portal Engine website to Kentico Cloud

### ISSUE THREAD

**Issue by jeroenfurst** [Kentico/ems-module-kontent-publishing#1]
I installed a clean version of the Dancing Goat (Portal Engine) website and followed the instructions to synchronize the content to Kentico Cloud. All seems to work fine except the synchronization of the Pages. Below you can find the error from the Event Log:

/Articles/Donate-with-us
Message: Object reference not set to an instance of an object.

I used a clean installation of Kentico 12 hotfix 29.

**Comment by Simply007** [comment]
Hello @jeroenfurst,

@kenticomartinh (author of this repository) is currently on the vacation. I believe he will take a look at it once he is back!

**Comment by AvoMeguerditchian** [comment]
Hello, we are also facing similar issues and was wondering if you were able to resolve this.  If so, can you share?

**Comment by mvaraga** [comment]
Hello @AvoMeguerditchian could you provide more information about your issue?
I've tried to synchronize Dancing Goat site on freshly installed Kentico 12 Service pack and everything worked without any problem.
