### ISSUE TITLE
Rename Kentico Cloud to Kentico Kontent in the repo

### ISSUE THREAD

**Issue by Simply007** [Kentico/ems-module-kontent-publishing#2]
### Brief bug description

As a part of Kentico Kontent rebranding, there are few things to adjust in this repository. 

As an example, it is possible to use  [.net delivery SDK](https://github.com/Kentico/kontent-delivery-sdk-net/pull/169)

### Expected behavior

* Rename Project
* Adjust the namespaces from `Kentico.KenticoCloudPublishing` to `Kentico.EMS.Kontent.CloudPublishing` or similar (keep in mind we would like to have the namespace `Kentico.Kontent.*` reserved for the code directly bound to Kentico Content product)
* Adjust the readme
* Change the repository name to `ems-module-cloud-publishing` to `ems-module-kontent-publishing`

### Additional context

Guidelines: https://gitter.im/Kentico/Kontent?at=5d8b643d692d464f7969c6d9

**Comment by Simply007** [comment]
Ping: @VaclavK2

**Comment by kenticomartinh** [comment]
Rebranded to Kentico Kontent

Module name: Kentico.KontentPublishing
Assembly and namespaces: Kentico.EMS.Kontent.Publishing

Screenshots and readme updated

**Comment by Simply007** [comment]
Closing:

* Implemented in https://github.com/Kentico/ems-module-kontent-publishing/commit/d9da4b1fb7a35b19acff365fac473670528f3b9c
